version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - openvpn
  openvpn:
    image: linuxserver/openvpn-as
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - openvpn:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
  # hello:
  #   image: nginx
  #   ports:
  #     - 8080:80
  #   environment:
  #     - NGINX_PORT=80
volumes:
  openvpn: