version: '2'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 143:143
      - 25:25
      - 110:110
      - 587:587
    env_file:
      - nginx.env
